---
- name: create default group
  sudo: yes
  group: name=lostechies state=present

- name: create wordpress user
  sudo: yes
  user: name={{ item }} shell=/bin/bash group=lostechies
  with_items:
    - jmeridth
    - cmissal
    - wordpress

- name: ensure .ssh folder exists
  file: path=/home/{{ item }}/.ssh state=directory
  with_items:
    - jmeridth
    - cmissal

- name: copy public key to authorized_keys
  authorized_key: user={{ item }} key="{{ lookup('file', '{{ item }}@id_rsa.pub') }}"
  with_items:
    - jmeridth
    - cmissal
